const equipment=[['motorcycle','Мотоцикл',['Өдөр','7 хоног','Сар']],['vehicle','Автомашин/трактор/ATV',['Өдөр','7 хоног','Сар']],['generator','Бензин/дизель генератор',['Өдөр','7 хоног','Сар']],['pump','Усны насос',['Өдөр','7 хоног','Сар']],['mower','Өвс хадагч/тэжээл бэлтгэгч',['Улирал','Сар']],['solar','Нарны хавтан, контроллер',['Тогтмол']],['battery','Аккумулятор, инвертер',['Тогтмол']],['welder','Гагнуурын аппарат',['7 хоног','Сар','Улирал']],['tools','Цахилгаан/гар багаж',['7 хоног','Сар','Улирал']],['other','Бусад',['Өдөр','7 хоног','Сар','Улирал']]];
function esc(s){return s.replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
document.getElementById('equipmentRows').innerHTML=equipment.map(([id,label,uses])=>`<tr><td>${esc(label)}${id==='other'?'<br><input type="text" name="J_other_equipment" placeholder="Нэр">':''}</td><td><select name="J_${id}_has"><option value="">-</option><option>Тийм</option><option>Үгүй</option></select></td><td><select name="J_${id}_use"><option value="">-</option>${uses.map(x=>`<option>${x}</option>`).join('')}</select></td><td><select name="J_${id}_break"><option value="">-</option><option>Үгүй</option><option>1</option><option>2+</option></select></td><td><select name="J_${id}_selfrepair"><option value="">-</option><option>Тийм</option><option>Үгүй</option></select></td></tr>`).join('');
const skills=[['daily','Өдөр тутмын үзлэг'],['oil','Тос/шүүлтүүр'],['spark','Очлуур'],['multimeter','Мультиметр'],['cable','Кабель/туйл шалгах'],['weld','Гагнуурын энгийн оёдол']];
document.getElementById('skillsRows').innerHTML=skills.map(([id,l])=>`<tr><td>${l}</td>${['Тийм','Тусламжтай','Үгүй'].map(v=>`<td><label><input type="radio" name="J4_${id}" value="${v}"> ${v}</label></td>`).join('')}</tr>`).join('');
const ppes=[['gloves','Ажлын бээлий'],['glasses','Нүдний шил'],['face','Нүүрний хаалт'],['welding','Гагнуурын баг'],['boots','Ажлын гутал'],['hearing','Чихний хамгаалалт']];
document.getElementById('ppeRows').innerHTML=ppes.map(([id,l])=>`<tr><td>${l}</td><td><label><input type="checkbox" name="I3_${id}_has" value="Тийм"> Байгаа</label></td><td><label><input type="checkbox" name="I3_${id}_use" value="Тийм"> Хэрэглэдэг</label></td></tr>`).join('');
const digital=[['photo','Зураг/видео'],['search','Мэдээлэл хайх'],['qr','QR унших'],['gps','GPS/газрын зураг'],['file','Файл илгээх'],['form','Онлайн маягт']];
document.getElementById('digitalRows').innerHTML=digital.map(([id,l])=>`<tr><td>${l}</td>${['Тийм','Тусламжтай','Үгүй'].map(v=>`<td><label><input type="radio" name="K1_${id}" value="${v}"> ${v}</label></td>`).join('')}</tr>`).join('');
const training=[['hse','ХАБЭА, PPE, гал, анхны тусламж'],['motor','Мотоцикл, жижиг хөдөлгүүрийн арчилгаа'],['genpump','Генератор, усны насос'],['welding','Ахуйн гагнуур'],['solar','Нарны хавтан, аккумулятор, инвертер'],['electric','Цахилгаан, мультиметр, бага хүчдэл'],['digital','Дижитал ур чадвар, цахим үйлчилгээ'],['ai','AI-ийг хариуцлагатай ашиглах'],['records','Өрхийн бүртгэл, зардал, хоршоо'],['processing','Малын ашиг шимийн анхан шатны боловсруулалт'],['other','Бусад']];
document.getElementById('trainingRows').innerHTML=training.map(([id,l])=>`<tr><td>${l}${id==='other'?'<br><input type="text" name="L_other_topic" placeholder="Бусад сэдэв">':''}</td>${[0,1,2,3].map(v=>`<td><label><input type="radio" name="L_score_${id}" value="${v}"> ${v}</label></td>`).join('')}</tr>`).join('');
const steps=[...document.querySelectorAll('.step')];let current=0;const bar=document.getElementById('bar'),stepLabel=document.getElementById('stepLabel'),pct=document.getElementById('pct');
function updateProgress(){const p=Math.round(((current+1)/steps.length)*100);bar.style.width=p+'%';pct.textContent=p+'%';stepLabel.textContent=`Хэсэг ${current+1}/${steps.length} · ${steps[current].dataset.title}`;window.scrollTo({top:0,behavior:'smooth'})}
function showStep(i){steps[current].classList.remove('active');current=i;steps[current].classList.add('active');steps[current].querySelector('.error')?.classList.remove('show');if(current===steps.length-1)renderReview();updateProgress()}
function visibleRequiredInvalid(step){const req=[...step.querySelectorAll('[required]')].filter(el=>el.offsetParent!==null);for(const el of req){if(el.type==='radio'){if(!step.querySelector(`[name="${el.name}"]:checked`))return el}else if(!el.value.trim())return el}return null}
function validateStep(step){const err=step.querySelector('.error');const bad=visibleRequiredInvalid(step);if(bad){err.textContent='* тэмдэгтэй заавал бөглөх талбарыг гүйцээнэ үү.';err.classList.add('show');bad.focus();return false}err?.classList.remove('show');return true}
document.addEventListener('click',e=>{if(e.target.classList.contains('next')){const step=steps[current];if(!validateStep(step))return;if(current===0){const c=document.querySelector('[name="B1_consent"]:checked')?.value;if(c==='Үгүй'){document.getElementById('refusal').classList.add('show');e.target.style.display='none';return}}if(current<steps.length-1)showStep(current+1)}if(e.target.classList.contains('prev')&&current>0)showStep(current-1)});
document.querySelectorAll('input[name="B2_phone_consent"]').forEach(x=>x.addEventListener('change',()=>{document.getElementById('phoneBox').classList.toggle('show',x.value==='Тийм'&&x.checked)}));
document.getElementById('incident').addEventListener('change',e=>document.getElementById('incidentTypes').classList.toggle('show',e.target.value&&e.target.value!=='Үгүй'));
document.addEventListener('change',e=>{if(e.target.matches('input[type="checkbox"][data-max]')&&e.target.checked){const name=e.target.name,max=Number(e.target.dataset.max),checked=[...document.querySelectorAll(`input[name="${name}"]:checked`)];if(checked.length>max){e.target.checked=false;alert(`Энэ асуултаас ${max} хүртэл сонгоно.`)}}});
function formObject(){const fd=new FormData(document.getElementById('survey'));const o={};for(const [k,v] of fd.entries()){if(o[k]!==undefined)o[k]=Array.isArray(o[k])?[...o[k],v]:[o[k],v];else o[k]=v}o._submitted_at=new Date().toISOString();return o}
function renderReview(){const o=formObject();const main=[['Аймаг',o.V2_aimag],['Сум',o.V2_soum],['Баг',o.V2_bag],['Нас',o.G1_age],['1-р хэрэгцээ',o.L1_priority_1],['Оролцох хугацаа',o.M1_duration],['Сургалтын сонирхол',o.M7_interest]];document.getElementById('review').innerHTML='<b>Гол мэдээллийн хяналт</b><br>'+main.map(([k,v])=>`${k}: <strong>${v||'—'}</strong>`).join('<br>')}
const BACKEND_URL='https://script.google.com/macros/s/AKfycbyG_Ng_YqE1C9aS5z4GvrlO3ye6kx0pezlMEgwsgszEndZqjo-KrgOpaf2SB1Rflz07IQ/exec';let submitting=false;
async function sendToBackend(data){const body=new URLSearchParams();body.set('payload',JSON.stringify(data));try{await fetch(BACKEND_URL,{method:'POST',mode:'no-cors',body,cache:'no-store'});return true}catch(fetchErr){return await new Promise((resolve,reject)=>{const frame=document.createElement('iframe');const frameName='mtu_submit_'+Date.now();frame.name=frameName;frame.style.display='none';frame.src='about:blank';const postForm=document.createElement('form');postForm.method='POST';postForm.action=BACKEND_URL;postForm.target=frameName;postForm.style.display='none';const payload=document.createElement('input');payload.type='hidden';payload.name='payload';payload.value=JSON.stringify(data);postForm.appendChild(payload);document.body.append(frame,postForm);let submitted=false,done=false;const cleanup=()=>{setTimeout(()=>{postForm.remove();frame.remove()},500)};frame.addEventListener('load',()=>{if(submitted&&!done){done=true;cleanup();resolve(true)}});setTimeout(()=>{try{submitted=true;postForm.submit();setTimeout(()=>{if(!done){done=true;cleanup();resolve(true)}},5000)}catch(err){cleanup();reject(err)}},50)})}}
function saveLocalBackup(data){try{const saved=JSON.parse(localStorage.getItem('mtu_pending_submissions')||'[]');saved.push(data);localStorage.setItem('mtu_pending_submissions',JSON.stringify(saved.slice(-20)))}catch(_){}}
function clearLocalBackup(id){try{const saved=JSON.parse(localStorage.getItem('mtu_pending_submissions')||'[]').filter(x=>x._submission_id!==id);localStorage.setItem('mtu_pending_submissions',JSON.stringify(saved))}catch(_){}}
document.getElementById('survey').addEventListener('submit',async e=>{e.preventDefault();if(submitting)return;let firstBad=null;for(const s of steps){const b=visibleRequiredInvalid(s);if(b){firstBad={s,b};break}}if(firstBad){showStep(steps.indexOf(firstBad.s));const err=firstBad.s.querySelector('.error');err.textContent='Заавал бөглөх талбар дутуу байна.';err.classList.add('show');firstBad.b.focus();return}const data=formObject();const id='MTU-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase();data._submission_id=id;saveLocalBackup(data);const submitBtn=e.submitter||document.querySelector('button[type="submit"]');const originalText=submitBtn?submitBtn.textContent:'';submitting=true;if(submitBtn){submitBtn.disabled=true;submitBtn.textContent='Илгээж байна...'}const errBox=steps[current].querySelector('.error');errBox?.classList.remove('show');try{await sendToBackend(data);clearLocalBackup(id);const success=document.getElementById('success');success.innerHTML=`<h3 style="margin-top:0">Амжилттай илгээгдлээ</h3><p>Бүртгэлийн ID: <b>${id}</b></p><p class="mini">Хариултыг судалгааны Google Sheet рүү илгээлээ. Бүртгэлийн ID-г шаардлагатай бол хадгална уу.</p><button type="button" id="newForm" class="btn secondary">Шинэ асуумж бөглөх</button>`;success.classList.add('show');document.getElementById('newForm').onclick=()=>location.reload();success.scrollIntoView({behavior:'smooth'});document.querySelector('button[type="submit"]').style.display='none'}catch(err){if(errBox){errBox.textContent='Илгээх үед сүлжээний алдаа гарлаа. Хариулт энэ төхөөрөмжид түр хадгалагдсан. Интернэтээ шалгаад дахин “Асуумж илгээх” дарна уу.';errBox.classList.add('show')}}finally{submitting=false;if(submitBtn&&submitBtn.style.display!=='none'){submitBtn.disabled=false;submitBtn.textContent=originalText}}});
updateProgress();